# Generated by Django 3.2.25 on 2025-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Under Review'), (3, 'Approved'), (4, 'Rejected')], default=1),
        ),
    ]
