# Generated by Django 3.2.25 on 2025-02-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_auto_20250228_1623'),
    ]

    operations = [
    ]
