# Generated by Django 3.2.25 on 2025-03-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_migrate_status_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_approved',
        ),
    ]
