# Generated by Django 3.2.25 on 2025-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='role',
            field=models.IntegerField(choices=[(1, 'Transaction Officer'), (2, 'Credit Analysis'), (3, 'Credit Manager'), (4, 'Admin'), (5, 'Audit')], max_length=20),
        ),
    ]
