# Generated by Django 3.2.25 on 2025-02-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_employeeaccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Credit Analysis'), (3, 'Credit Manager'), (4, 'Transaction Officer'), (5, 'Audit')]),
        ),
    ]
