# Generated by Django 3.2.25 on 2025-03-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employeeaccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaccount',
            name='is_staff',
        ),
    ]
