# Generated by Django 3.2.25 on 2025-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250329_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
