# Generated by Django 3.2.25 on 2025-04-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250412_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
